/**
 * Curated "personalization presets" for Settings → Custom colors (Pro). Each
 * preset is a full coordinated set — background, text, and a derived accent
 * pair for buttons/highlights — not just a bg/fg pair, so picking one always
 * looks intentional (the same promise `AccentPicker`'s six project accents
 * already make). Every preset keeps Aurora's "glass over parchment" aesthetic
 * (DESIGN-GUIDELINES.md §0-3/§11) in a different hue: same warm-glass
 * construction, same restraint (one accent family per surface), just a
 * different ink-on-paper pairing than the brand's own oxblood-on-parchment.
 *
 * Every bg/text pair and every accentFg/accentFrom+accentTo pair here clears
 * WCAG AA (>= 4.5:1) BY CONSTRUCTION — verified in
 * `personalizationPresets.test.ts` using the same `contrastRatio` math the
 * rest of the app relies on (`lib/contrast.ts`) — not by warning the user
 * after the fact the way the raw hex pickers (Advanced) still do.
 */
import { contrastRatio } from './contrast';

export type PersonalizationPresetId =
  | 'slate-ink'
  | 'terracotta-sun'
  | 'deep-forest'
  | 'dusty-clay'
  | 'harbor-blue'
  | 'amber-study'
  | 'plum-study'
  | 'sage-parchment';

export interface PersonalizationPreset {
  label: string;
  description: string;
  /** Page background. */
  bg: string;
  /** Primary text color. */
  text: string;
  /** Gradient accent stops for buttons/tiles (`--accent-from`/`--accent-to`). */
  accentFrom: string;
  accentTo: string;
  /** Text color that clears AA on top of BOTH accent stops. */
  accentFg: string;
}

/**
 * Eight coordinated sets, each the Almanac's warm-glass construction in a
 * different hue family. Values were generated by walking the accent's HSL
 * lightness until both gradient stops cleared AA against a fixed bone/ink
 * foreground (see the design session's derivation script) — the same
 * approach `deriveAccentFromColor` below applies live to Advanced custom
 * colors, just pre-computed and hand-named here for curation.
 */
export const PERSONALIZATION_PRESETS: Record<PersonalizationPresetId, PersonalizationPreset> = {
  'slate-ink': {
    label: 'Slate Ink',
    description: 'Cool indigo-slate on a soft grey parchment.',
    bg: '#E4E6E2',
    text: '#23282B',
    accentFrom: '#365A91',
    accentTo: '#486EA8',
    accentFg: '#F7F1E6',
  },
  'terracotta-sun': {
    label: 'Terracotta Sun',
    description: 'Warm terracotta ink on sun-baked parchment.',
    bg: '#F1E2D3',
    text: '#3B2118',
    accentFrom: '#8D4634',
    accentTo: '#A45946',
    accentFg: '#F7F1E6',
  },
  'deep-forest': {
    label: 'Deep Forest',
    description: 'Pale mint on a deep forest-ink page.',
    bg: '#16211B',
    text: '#E7EEE3',
    accentFrom: '#24613A',
    accentTo: '#34794D',
    accentFg: '#F7F1E6',
  },
  'dusty-clay': {
    label: 'Dusty Clay',
    description: 'Warm rose-clay ink on a blushed parchment.',
    bg: '#EFE1DD',
    text: '#3A2420',
    accentFrom: '#9C3A47',
    accentTo: '#B34D5A',
    accentFg: '#F7F1E6',
  },
  'harbor-blue': {
    label: 'Harbor Blue',
    description: 'Nautical teal-blue ink on a cool grey parchment.',
    bg: '#E2E7E9',
    text: '#1D2B30',
    accentFrom: '#275F68',
    accentTo: '#377781',
    accentFg: '#F7F1E6',
  },
  'amber-study': {
    label: 'Amber Study',
    description: "Old-library gold ink on a warm amber parchment.",
    bg: '#F0E4C8',
    text: '#3A2C10',
    accentFrom: '#6C5528',
    accentTo: '#846B39',
    accentFg: '#F7F1E6',
  },
  'plum-study': {
    label: 'Plum Study',
    description: 'Pale mauve on a deep plum-ink page.',
    bg: '#201220',
    text: '#EDE1E8',
    accentFrom: '#953773',
    accentTo: '#AB4987',
    accentFg: '#F7F1E6',
  },
  'sage-parchment': {
    label: 'Sage Parchment',
    description: 'Deep sage ink on a muted green-grey parchment.',
    bg: '#E7E9DC',
    text: '#263323',
    accentFrom: '#3C6124',
    accentTo: '#507934',
    accentFg: '#F7F1E6',
  },
};

export const PERSONALIZATION_PRESET_IDS = Object.keys(
  PERSONALIZATION_PRESETS,
) as PersonalizationPresetId[];

export function isPersonalizationPresetId(value: string): value is PersonalizationPresetId {
  return Object.prototype.hasOwnProperty.call(PERSONALIZATION_PRESETS, value);
}

const BONE = '#F7F1E6';
const INK = '#221A14';
/** AA target for normal text, mirrored from `lib/contrast.ts`'s `AA_CONTRAST`
 *  (kept as a literal here so this stays a small, dependency-light module —
 *  the shared constant is still the one the test file asserts against). */
const AA = 4.5;

/** `#rrggbb` -> `[h, s, l]` (h in 0-360, s/l in 0-100). */
function hexToHsl(hex: string): [number, number, number] {
  const clean = hex.replace('#', '');
  const n = Number.parseInt(clean, 16);
  const r = ((n >> 16) & 255) / 255;
  const g = ((n >> 8) & 255) / 255;
  const b = (n & 255) / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  let h = 0;
  let s = 0;
  const l = (max + min) / 2;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r:
        h = (g - b) / d + (g < b ? 6 : 0);
        break;
      case g:
        h = (b - r) / d + 2;
        break;
      default:
        h = (r - g) / d + 4;
    }
    h /= 6;
  }
  return [h * 360, s * 100, l * 100];
}

/** `[h, s, l]` (h in 0-360, s/l in 0-100) -> `#rrggbb`. */
function hslToHex(h: number, s: number, l: number): string {
  const S = s / 100;
  const L = l / 100;
  const k = (n: number) => (n + h / 30) % 12;
  const a = S * Math.min(L, 1 - L);
  const f = (n: number) => L - a * Math.max(-1, Math.min(k(n) - 3, Math.min(9 - k(n), 1)));
  const to2 = (v: number) =>
    Math.max(0, Math.min(255, Math.round(255 * v)))
      .toString(16)
      .padStart(2, '0');
  return `#${to2(f(0))}${to2(f(8))}${to2(f(4))}`;
}

export interface DerivedAccent {
  from: string;
  to: string;
  /** Whichever of bone/ink clears AA against both stops. */
  fg: string;
}

/**
 * Derive a coordinated accent pair from an arbitrary hex (used for Advanced
 * custom colors, where the user picks their own bg/text outside the curated
 * presets). Keeps the hue, floors the saturation so a near-grey pick still
 * reads as a color, then walks lightness from vivid toward dark until both
 * gradient stops clear AA (>= 4.5:1) against a fixed light or dark
 * foreground — same shape as `readableOnTint` in `lib/contrast.ts`, applied
 * to a gradient pair instead of a single tint. Deterministic and always
 * AA-compliant: the final fallback step forces black/white-level contrast.
 */
export function deriveAccentFromColor(hex: string): DerivedAccent {
  const [h] = hexToHsl(hex);
  const sat = 46;
  const gap = 8;

  for (let l = 46; l >= 20; l -= 1) {
    const from = hslToHex(h, sat, l);
    const to = hslToHex(h, Math.max(sat - 6, 25), Math.min(l + gap, 54));
    if (contrastRatio(from, BONE) >= AA && contrastRatio(to, BONE) >= AA) {
      return { from, to, fg: BONE };
    }
  }
  for (let l = 55; l >= 8; l -= 1) {
    const from = hslToHex(h, sat, l);
    const to = hslToHex(h, Math.max(sat - 6, 25), Math.min(l + gap, 62));
    const boneOk = contrastRatio(from, BONE) >= AA && contrastRatio(to, BONE) >= AA;
    const inkOk = contrastRatio(from, INK) >= AA && contrastRatio(to, INK) >= AA;
    if (boneOk || inkOk) return { from, to, fg: boneOk ? BONE : INK };
  }
  // Unreachable in practice (the loops above cover the full lightness range
  // for any hue/saturation), but keep a hard-AA fallback rather than ever
  // returning an unverified pair.
  return { from: '#000000', to: '#1a1a1a', fg: BONE };
}
