import { supabase } from '@/lib/supabase';
import type { TodoItem, TodoList, TodoRecurrence } from '@/types/database';
import type { RecurrenceRule } from './recurrence';

/**
 * Supabase data layer for the daily to-do planner. Every call is governed by Row
 * Level Security (plan.md §6): the lists/items are private to their owner, so
 * these functions never filter by user — the database only returns and accepts
 * the caller's own rows. The hooks in useTodos.ts add caching + optimistic
 * updates. user_id defaults to auth.uid() in the DB, so inserts omit it.
 */

export interface TodosData {
  lists: TodoList[];
  items: TodoItem[];
}

/** All of a day's lists and their items (RLS scopes both to the current user). */
export async function fetchTodos(dateKey: string): Promise<TodosData> {
  const { data: lists, error: listsError } = await supabase
    .from('todo_lists')
    .select('*')
    .eq('list_date', dateKey)
    .order('position', { ascending: true });
  if (listsError) throw listsError;
  if (lists.length === 0) return { lists, items: [] };

  const { data: items, error: itemsError } = await supabase
    .from('todo_items')
    .select('*')
    .in(
      'list_id',
      lists.map((list) => list.id),
    )
    .order('position', { ascending: true });
  if (itemsError) throw itemsError;
  return { lists, items };
}

// --- Lists ------------------------------------------------------------------

export async function insertTodoList(input: {
  dateKey: string;
  name: string;
  position: number;
  /** Set when this list is being auto-generated by a recurrence rule, so it's
   *  recognised as "already generated for this day" and never duplicated. */
  sourceRecurrenceId?: string;
}): Promise<TodoList> {
  const { data, error } = await supabase
    .from('todo_lists')
    .insert({
      list_date: input.dateKey,
      name: input.name,
      position: input.position,
      source_recurrence_id: input.sourceRecurrenceId ?? null,
    })
    .select('*')
    .single();
  if (error) throw error;
  return data;
}

/** Link an existing list to the recurrence template that now governs it (or
 *  clear the link by passing `null`). Used when a user turns repeat on/off for
 *  a list they already created by hand. */
export async function setTodoListRecurrence(id: string, recurrenceId: string | null): Promise<TodoList> {
  const { data, error } = await supabase
    .from('todo_lists')
    .update({ source_recurrence_id: recurrenceId })
    .eq('id', id)
    .select('*')
    .single();
  if (error) throw error;
  return data;
}

export async function renameTodoList(id: string, name: string): Promise<TodoList> {
  const { data, error } = await supabase
    .from('todo_lists')
    .update({ name })
    .eq('id', id)
    .select('*')
    .single();
  if (error) throw error;
  return data;
}

/** Move a list to a new fractional position (drag-reorder of whole lists). */
export async function updateTodoListPosition(id: string, position: number): Promise<TodoList> {
  const { data, error } = await supabase
    .from('todo_lists')
    .update({ position })
    .eq('id', id)
    .select('*')
    .single();
  if (error) throw error;
  return data;
}

/** Delete a list. Its items cascade-delete (ON DELETE CASCADE). */
export async function removeTodoList(id: string): Promise<void> {
  const { error } = await supabase.from('todo_lists').delete().eq('id', id);
  if (error) throw error;
}

// --- Items ------------------------------------------------------------------

export async function insertTodoItem(input: {
  listId: string;
  text: string;
  position: number;
}): Promise<TodoItem> {
  const { data, error } = await supabase
    .from('todo_items')
    .insert({ list_id: input.listId, text: input.text, position: input.position })
    .select('*')
    .single();
  if (error) throw error;
  return data;
}

export async function updateTodoItem(
  id: string,
  patch: { text?: string; is_done?: boolean; position?: number; priority?: number | null },
): Promise<TodoItem> {
  const { data, error } = await supabase
    .from('todo_items')
    .update(patch)
    .eq('id', id)
    .select('*')
    .single();
  if (error) throw error;
  return data;
}

export async function removeTodoItem(id: string): Promise<void> {
  const { error } = await supabase.from('todo_items').delete().eq('id', id);
  if (error) throw error;
}

// --- Recurrences --------------------------------------------------------
// User-global (not per-day) — every active rule is evaluated client-side
// against whichever day is being viewed. See recurrence.ts for the rule
// shapes and ruleMatchesDate().

/** All of the signed-in user's active recurrence templates. */
export async function fetchRecurrences(): Promise<TodoRecurrence[]> {
  const { data, error } = await supabase
    .from('todo_recurrences')
    .select('*')
    .eq('active', true)
    .order('created_at', { ascending: true });
  if (error) throw error;
  return data;
}

export async function insertRecurrence(input: {
  name: string;
  items: string[];
  rule: RecurrenceRule;
}): Promise<TodoRecurrence> {
  const { data, error } = await supabase
    .from('todo_recurrences')
    .insert({ name: input.name, items: input.items, rule: input.rule })
    .select('*')
    .single();
  if (error) throw error;
  return data;
}

export async function updateRecurrence(
  id: string,
  patch: { name?: string; items?: string[]; rule?: RecurrenceRule },
): Promise<TodoRecurrence> {
  const { data, error } = await supabase
    .from('todo_recurrences')
    .update(patch)
    .eq('id', id)
    .select('*')
    .single();
  if (error) throw error;
  return data;
}

/** Deleting a recurrence stops future regeneration; already-created lists
 *  stay put (their `source_recurrence_id` just goes null via ON DELETE SET NULL). */
export async function removeRecurrence(id: string): Promise<void> {
  const { error } = await supabase.from('todo_recurrences').delete().eq('id', id);
  if (error) throw error;
}
