-- Aurora — MCP (Model Context Protocol) personal access token.
--
-- Lets a Pro+ user connect Claude Desktop/Code directly to their Aurora
-- account (read/write boards, to-dos, notes) via a scoped, revocable token —
-- see SETUP-MCP.md for the full design record and supabase/README.md for
-- deployment. Unlike `calendar_feed_token` (plaintext, read-only, low
-- stakes), this token grants read/write access to the user's whole account,
-- so ONLY A HASH IS EVER STORED. The plaintext is generated by the
-- `mcp-token` edge function and shown to the user exactly once; it can never
-- be retrieved again, only rotated (which invalidates the old one) or
-- revoked.
--
-- Only the service role may write these columns (mirrors
-- protect_calendar_feed_token() in 20260813020000_calendar_feed_token.sql) —
-- they are set exclusively by the `mcp-token` edge function, never by the
-- client directly.

alter table public.profiles
  add column if not exists mcp_token_hash text null unique,
  add column if not exists mcp_token_created_at timestamptz null,
  add column if not exists mcp_token_last_used_at timestamptz null;

comment on column public.profiles.mcp_token_hash is
  'SHA-256 hex digest of the current Aurora MCP access token. Set only by the mcp-token edge function; the plaintext is never stored. Null = no token issued / revoked.';
comment on column public.profiles.mcp_token_created_at is
  'When the current MCP token was generated/rotated. Set only by the mcp-token edge function.';
comment on column public.profiles.mcp_token_last_used_at is
  'Best-effort last-successful-auth timestamp, updated by the mcp-server edge function on each authenticated tool call. Not authoritative for security decisions — display only.';

create or replace function public.protect_mcp_token_columns()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if coalesce(auth.jwt() ->> 'role', '') <> 'service_role' then
    if new.mcp_token_hash is distinct from old.mcp_token_hash
      or new.mcp_token_created_at is distinct from old.mcp_token_created_at
      or new.mcp_token_last_used_at is distinct from old.mcp_token_last_used_at
    then
      raise exception 'The MCP access token can only be changed by the MCP token system.';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists protect_mcp_token_columns on public.profiles;
create trigger protect_mcp_token_columns
  before update on public.profiles
  for each row
  execute function public.protect_mcp_token_columns();
